### ISSUE TITLE
Does not compile on FreeBSD 9.3

### ISSUE THREAD

**Issue by jstarcher** [duosecurity/duo_openvpn#12]
While trying to compile the package on FreeBSD 9.3 I receive the following error:

```
$ make
"Makefile", line 4: Need an operator
"Makefile", line 7: Need an operator
"Makefile", line 9: Need an operator
"Makefile", line 23: Need an operator
"Makefile", line 25: Need an operator
"Makefile", line 27: Need an operator
make: fatal errors encountered -- cannot continue
```

I figured what a make vs gmake issue so I used gmake:

```
$ gmake
cc -DPREFIX='"/opt/duo"' -fPIC -c duo_openvpn.c
cc -fPIC -shared -Wl,-soname,duo_openvpn.so -o duo_openvpn.so duo_openvpn.o -lc
```

Success! However, gmake install fails:

```
$  sudo gmake install
mkdir -p /opt/duo
install -c duo_openvpn.so -m 755 /opt/duo
install: -m: No such file or directory
Makefile:20: recipe for target 'install' failed
gmake: *** [install] Error 71
```

make install fails as well. Is FreeBSD 9.x not supported?

**Comment by lidow** [comment]
I've manged to move further by changing 
`install -c -m 755 duo_openvpn.so /opt/duo`
....

I also add 
`#include <sys/wait.h>` in `duo_openvpn.c` for FreeBSD10.3

Anyway, It does not work when added in openvpn, I don't see errors.

**Comment by 2bithacker** [comment]
I suspect there's an issue around the PATH environment. 

When running OpenVPN myself, with /usr/local/bin in my PATH, it works fine. When starting OpenVPN from it's rc.d script, I think PATH gets scrubbed and does not include /usr/local/bin, so when `duo_openvpn.so` calls out to `duo_openvpn.py`, it's failing to find the Python interpreter.

**Comment by petiepooo** [comment]
Your wish has been answered by #37!

@jstarcher if you're still on github, please check out the port and close this issue.

**Comment by AaronAtDuo** [comment]
Closing out old tickets
