### ISSUE TITLE
missing symbol on SmartOS 64 bit

### ISSUE THREAD

**Issue by numericillustration** [duosecurity/duo_openvpn#15]
I found that compiling this on a 64bit SmartOS image works but when trying to start openvpn with this  as a module I would yield the error:

PLUGIN_INIT: could not load plugin shared object /opt/duo/duo_openvpn.so: ld.so.1: openvpn: fatal: relocation error: file /opt/duo/duo_openvpn.so: symbol WIFEXITED: referenced symbol not found

This symbol can be found in /usr/include/sys/wait.h and adding an additional import statement to duo_openvpn.c fixed it.
`#include <sys/wait.h>`

I see that the main openvpn source includes <sys/wait.h> in multiple places
https://github.com/OpenVPN/openvpn/blob/4507bb6cd11799f72f1ede602315a60e03bb449c/src/plugins/auth-pam/auth-pam.c#L46

https://github.com/OpenVPN/openvpn/blob/2282b1be7968ef44accde705ccc64addab6d77ba/src/plugins/down-root/down-root.c#L40

Also, looks like this is the same issue addressed by https://github.com/duosecurity/duo_openvpn/pull/13

**Comment by BradleyHiggins** [comment]
#13 has been merged.

Thanks for using Duo!
