### ISSUE TITLE
2FA broken on OpenVPN 2.4.1 (CentOS, Fedora, RHEL)

### ISSUE THREAD

**Issue by jasonbeitler** [duosecurity/duo_openvpn#19]
After updating to OpenVPN 2.4.1 I see the following error after starting OpenVPN.

```
> systemctl status openvpn@server.service
> ● openvpn@server.service - OpenVPN Robust And Highly Flexible Tunneling Application On server
>    Loaded: loaded (/usr/lib/systemd/system/openvpn@.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Wed 2017-05-03 23:15:35 EDT; 9s ago
>   Process: 3378 ExecStart=/usr/sbin/openvpn --cd /etc/openvpn/ --config %i.conf (code=exited, status=1/FAILURE)
>  Main PID: 3378 (code=exited, status=1/FAILURE)
> 
> May 03 23:15:35 123456 systemd[1]: Starting OpenVPN Robust And Highly Flexible Tunn......
> May 03 23:15:35 123456 systemd[1]: openvpn@server.service: main process exited, cod...URE
> May 03 23:15:35 123456 systemd[1]: Failed to start OpenVPN Robust And Highly Flexib...er.
> May 03 23:15:35 123456 systemd[1]: Unit openvpn@server.service entered failed state.
> May 03 23:15:35 123456 systemd[1]: openvpn@server.service failed.
> Hint: Some lines were ellipsized, use -l to show in full.
```

Looking at the openvpn.log I see the following

```
> Options error: Unrecognized option or missing or extra parameter(s) in server.conf:314: plugin (2.4.1)
> Use --help for more information.
```

So then I look at my server.conf line 314 and that is the duo plugin

`plugin /opt/duo/duo_openvpn.so (Ikey,skey,api omitted)`

So the man page does not really say anything changed, but I did update to the latest version of the openvpn plugin from here [https://duo.com/docs/openvpn](https://duo.com/docs/openvpn). That did not help. I also verified the ikey,skey,api were correct. 

So as a test I just comment out this line

`#plugin /opt/duo/duo_openvpn.so (ikey,skey,api omitted)`

Bingo, it now works

```
systemctl status openvpn@server.service
● openvpn@server.service - OpenVPN Robust And Highly Flexible Tunneling Application On server
   Loaded: loaded (/usr/lib/systemd/system/openvpn@.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-05-03 23:22:02 EDT; 2s ago
 Main PID: 3493 (openvpn)
   Status: "Initialization Sequence Completed"
   CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
           └─3493 /usr/sbin/openvpn --cd /etc/openvpn/ --config server.conf

May 03 23:22:02 123456 systemd[1]: Starting OpenVPN Robust And Highly Flexible Tunn......
May 03 23:22:02 123456 systemd[1]: Started OpenVPN Robust And Highly Flexible Tunne...er.
Hint: Some lines were ellipsized, use -l to show in full.
```

Any thoughts, ideas?

**Comment by jasonbeitler** [comment]
Sorry hit submit to soon here is some more info

I have a CentOS 7 setup to patch nightly and reboot on the 1st (so apply kernel updates). It looks like OpenVPN 2.4.1 was dropped on 9 April, looking at the yum install logs I see this

`Apr 09 00:01:06 Updated: openvpn-2.4.1-2.el7.x86_64`

So this does not really effect anything until the service is restarted and or the machine is rebooted. I also ran across this post [https://community.duo.com/t/latest-openvpn-update-v2-4-1-2-breaks-duo-openvpn-so/1079](https://community.duo.com/t/latest-openvpn-update-v2-4-1-2-breaks-duo-openvpn-so/1079) and the fix I guess is to just roll back for this guy? There is no real follow up on the issue on that post.

**Comment by BradleyHiggins** [comment]
Hi Jason,
  Are your ikey, skey and api host configured with single back ticks in your server.conf file? See the section in the docs, under "OpenVPN 2.4 and later" for an example: https://duo.com/docs/openvpn#configure-the-server

**Comment by jasonbeitler** [comment]
I did miss that setting completely. You might just change the formatting to Note that like you do with reneg-sec. 

However just tried it and same error unfortunately.

**Comment by jasonbeitler** [comment]
Actually it is working now. It looks like the doc says use `ikey skey api` but if you use 'ikey skey api' it does work. 

Not sure if this is something to do with CentOS vs Debian (note I have not tested on Debian)?

**Comment by BradleyHiggins** [comment]
Awesome, happy to hear you're up and running!
I understand you're saying that backticks don't work, but single quotes do. I doubt this is related to the O/S. I'll go investigate a bit, and make sure our docs are correct.
Thanks for the report, and thanks for using Duo!
