### ISSUE TITLE
Certificate validation failure when using proxy

### ISSUE THREAD

**Issue by jescholl** [duosecurity/duo_openvpn#22]
The copy of `https_wrapper.py` in this repo seems to suffer from https://github.com/duosecurity/duo_openvpn_as/issues/3. It looks like it was fixed in [duo_openvpn_as](https://github.com/duosecurity/duo_openvpn_as/commit/ff8c9cce62b28e4312addfb64c566c8363b37d17) as well as [duo_client_python](https://github.com/duosecurity/duo_client_python/commit/5ccf34da4179473c3b354c08fc46d8ba316970eb) but the [documentation for openvpn](https://duo.com/docs/openvpn#build-and-install-the-plugin) point to this repo.

**Comment by rlynch1** [comment]
Hey Jason, thanks for bringing this to our attention! This issue is also being tracked right now and we'll see what we can do about it- hopefully your solution plays nicely with testing, but if not, we'll see if there's another way.
