### ISSUE TITLE
Unable to load duo_openvpn.so in OpenVpn server v. 2.4.6

### ISSUE THREAD

**Issue by jberlet** [duosecurity/duo_openvpn#26]
Hello,
I recently built and installed the duo_openvpn.so plugin on my openvpn server (version 2.4.6) and after installation/configuration of the plugin I am getting the following error on startup of openvpn:

openvpn[2547]: Options error: Unrecognized option or missing or extra parameter(s) in /tmp/openvpn/openvpn.conf:33: plugin (2.4.6)

This line (#33) in in the openvpn.conf that generated this error is as follows:
plugin /opt/duo/duo_openvpn.so ‘xxxxx yyyyyy zzzzzzzzz’

Note: I am using single quote to enclose the keys 'x y z'

This issue was supposedly fixed according to this submission by using the single quote:
https://github.com/duosecurity/duo_openvpn/issues/19

I have tried using double quotes and no-quotes but the error is the same after restarting the openvpn server. Because of this error, openvpn server fails to start and I have commented out loading of the duo plugin for now.

Is this a known/open issue with OpenVpn 2.4.6?

Thank you.
J

**Comment by AaronAtDuo** [comment]
@jberlet Sorry to hear you're having trouble!  We haven't heard of any issues with this, but give us a day or two to look into it and we'll get back to you.

**Comment by lgreerduo** [comment]
@jberlet, an error to start the OpenVPN service with the above resulting error typically means there is an issue with the syntax of the config file, as you have noted. I haven't been able to reproduce the error that you are seeing so I am curious though for more details. What OS are you currently running with specific version? 

If you want to get more immediate help, the Duo Support Team is always at your disposal as well via phone, email, or chat. Check out, https://duo.com/support, for the details.

**Comment by lshahar** [comment]
I have also issue with OpenVPN 2.4.7 using Amazon AMI 
Getting only 
Wed Jul 31 22:59:16 2019 5.102.205.241:58019 PUSH: Received control message: 'PUSH_REQUEST'
Wed Jul 31 22:59:22 2019 5.102.205.241:58019 PUSH: Received control message: 'PUSH_REQUEST'
Wed Jul 31 22:59:27 2019 5.102.205.241:58019 PUSH: Received control message: 'PUSH_REQUEST'
Wed Jul 31 22:59:32 2019 5.102.205.241:58019 PUSH: Received control message: 'PUSH_REQUEST'

but not push to approve...

**Comment by jberlet** [comment]
Hi - I determined the issue using the duo_openvpn plugin OpenVpn was not a
compatibility problem with OpenVpn. The PUSH request but no response is
likely an OpwnVpn config. issue either in the client or server


J

**Comment by petiepooo** [comment]
@jberlet if this is indeed a config problem, please close this.  Github issues are intended for code errors, not user errors or support requests... ;)

**Comment by AaronAtDuo** [comment]
Closing as this seems to have been a config issue
