### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by kzw** [duosecurity/duo_openvpn#27]
When do we expect support for python3?  Python 2 is about to be discontinued. We are in the process of upgrading our os and prefer to not support python2 to run this openvpn plugin.  Is this on the roadmap?

**Comment by petiepooo** [comment]
It should be an easy port.  Have you tried anything yet?  Pull requests are appreciated...

**Comment by petiepooo** [comment]
PR #28 submitted, but not yet tested.  @kzw, if you have a good test environment, please give it a whirl.

**Comment by jdoss** [comment]
Can this get tested and merged? Duo_OpenVPN doesn't work on CentOS 8 due to it shipping Python 3 by default. Also Python 2 is EOL in 18 days.

**Comment by xdesai** [comment]
Hey Joe and others!
It's on our roadmap to get done 🔜
Keep an eye out in the next week or so! Thanks for your patience and sorry for the delay.

**Comment by jdoss** [comment]
Sounds good @xdesai! Thanks!

**Comment by petiepooo** [comment]
This is complete.  Please close this issue.

**Comment by xdesai** [comment]
Thanks for reminding us @petiepooo !
