### ISSUE TITLE
Allow Duo script directory to be defined separately from Duo script name

### ISSUE THREAD

**Issue by floatingatoll** [duosecurity/duo_openvpn#4]
Whether -DUSE_PERL is true or false, it would be useful to define a single location for Duo scripts of all languages, so that the same "script directory" value can be used for both Perl and Python deployments.

This would likely require a new variable, DUO_SCRIPT_DIR, that when set (and DUO_SCRIPT_PATH unset), calculates the appropriate DUO_SCRIPT_PATH for either .py or .pl based on -DUSE_PERL.

**Comment by AaronAtDuo** [comment]
Closing out this old issue
