### ISSUE TITLE
Ignoring SIG_CHLD breaks external scripts

### ISSUE THREAD

**Issue by petiepooo** [duosecurity/duo_openvpn#9]
Commit 3b890e6 added a call to signal() to ignore SIG_CHLD.  While this prevents zombie processes, it breaks external script launches in openvpn, such as with the --learn-address option.  Specifically, it causes waitpid() at https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/misc.c#L315 to return ECHILD, which then cascades into other failures such as not routing between endpoints because the internal routing was not added.  See https://forums.openvpn.net/topic20888.html for my earlier discussion with a rather rude openvpn contributor...

I would suggest daemonizing the child process instead of ignoring SIG_CHLD.  That way, init (or systemd in later distros) will clean it up upon exit.

**Comment by owling** [comment]
I'm experiencing exactly the same, this issue is breaking IPv6 support for my openvpn client as I can't control the ndp proxy anymore via an external script.

**Comment by owling** [comment]
I've commented out line line 64 signal(SIGCHLD, SIG_IGN); and recompiled it a temporary fix to keep it working, hopefully a more permanent fix can be made by duo?

**Comment by owling** [comment]
Another solution which pevents zombies is to change line 99:
`exit(1);`
To:
`exit(0)`

**Comment by mschwager** [comment]
Hey, thanks for bringing this to our attention! It looks like you've gotten a pretty good grasp of the issue, and a workaround as well. I'll take a look at this when I get the opportunity. In the mean time, if you wanted to open up a PR with a suitable fix I'd welcome that as well :)

**Comment by petiepooo** [comment]
How does that work? The call to execve() should not return. If it ever hits the exit call after that it's because execve failed.

**Comment by owling** [comment]
I've made a permanent fix in PR #10

**Comment by petiepooo** [comment]
I don't think waitpid is the solution. It should be daemonized so PID 1 reaps it.

**Comment by petiepooo** [comment]
@owling, can you please try PR #11 and see if that works for you?  If you turn up your openvpn server's log verbage, you should see a difference between your patch and this one in what the server does between the initial auth call and when auth is granted.

To download the patched code, clone https://github.com/petiepooo/duo_openvpn, switch to the fix-SIG_IGN branch, and compile.  Thanks!

**Comment by petiepooo** [comment]
I see it's merged.  Thanks!  Glad to help out.

**Comment by mschwager** [comment]
Fixed in https://github.com/duosecurity/duo_openvpn/pull/11. Cheers!
